# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
os:
  editPreset: "nvim"
gui:
  commandLogSize: 50
  sidePanelWidth: 0.25
customCommands:
  - key: "O"
    context: "localBranches"
    command: "gh pr create --web"
  - key: "V"
    context: "localBranches"
    command: "gh pr view --web"
  - key: "C"
    context: "localBranches"
    command: "git commit"
    subprocess: true
  - key: "C"
    context: "files"
    prompts:
      - type: "input"
        title: "git commit msg --no-verify"
        key: "Message"
        initialValue: ""
    command: "git commit -m '{{.Form.Message}}' --no-verify"
